find ./  -name  *.bin  | xargs rm -rf
find ./  -name  *.dat  | xargs rm -rf
find ./  -name  *.rule  | xargs rm -rf
find ./  -name  *.av  | xargs rm -rf
find ./  -name  *.urlibx  | xargs rm -rf
find ./  -name  *.nti  | xargs rm -rf
find ./  -name  *.urlib  | xargs rm -rf
find ./  -name  *.wcs  | xargs rm -rf
find ./  -name  *.wcl  | xargs rm -rf
find ./  -name  *.nti  | xargs rm -rf
find ./  -name  *.geo  | xargs rm -rf